# --- Day 9: Rope Bridge ---
This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

`R 4`   
`U 4`   
`L 3`   
`D 1`   
`R 4`   
`D 1`   
`L 5`   
`R 2`    

This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?

In [1]:
import numpy as np

In [2]:
d = """R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2"""

In [3]:
instructions = d.split("\n")

In [4]:
def howBigIsMyGrid(txt):
    """
    
    """
    width = 1
    max_width = 1
    min_width = 0
    height = 1
    max_height = 1
    min_height = 0
    for instruction in txt.split("\n"):
        direction, amount = instruction.split(" ")
    
        if direction == "R":
            width += int(amount)
            if width > max_width:
                max_width = width
        elif direction == "L":
            width -= int(amount)
            if width < min_width:
                min_width = width

        elif direction == "U":
            height += int(amount)
            if height > max_height:
                max_height = height
        else:
            height -= int(amount)
            if height < min_height:
                min_height = height

    print("dimensions are: Height " + str(max_height - min_height) + "start x = " + str(-1*min_height) + " Width " + str(max_width - min_width) + "start y = " + str(-1*min_width))

In [5]:
np.zeros((5, 6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [6]:
howBigIsMyGrid(d)

dimensions are: Height 5start x = 0 Width 6start y = 0


## What do we need

+ Attributes
    + Start position
    + Head location
    + Tail location
    + Grid
    + Locations visited by the tail
    
+ Methods
    + Move head
    + Move tail



In [7]:
#gameBoard = np.zeros((5, 6), dtype=int)

In [8]:
class Game:
    def __init__(self, gameBoard, start):
        self.start = start
        self.startPosition = self.start
        self.headPosition = self.start
        self.tailPosition = self.start
        self.grid = gameBoard
        

    def gameStart(self):
        self.grid[self.start[0], self.start[0]] = 1
    
    def moveHead(self, instruction):
        direction, amount = instruction.split(" ")
        headLocation = self.headPosition
        
        #MOVE RIGHT
        if direction == "R" or direction == "L":
            verticle = 0
            if direction == "R":
                horizontal = 1
                #print("Horizontal")
            else:
                horizontal = -1
        else:
            horizontal = 0
            if direction == "U":
                verticle = 1
            else:
                verticle = -1
            
        for i in range(int(amount)):
            #move head
            movement = np.array([verticle, horizontal])
            self.headPosition += movement
            #print("move")
                        
            #check tail
            diff = self.headPosition - self.tailPosition
            # move diagonally
            #print(diff[1])
           
            #up and right
            if diff[0] == 2 and diff[1] ==1 or diff[0] == 1 and diff[1] == 2:
                self.tailPosition += np.array([1, 1])
            
            #up and left
            elif diff[0] == 2 and diff[1] == -1 or diff[0] == 1 and diff[1] == -2:
                #print("up and left")
                self.tailPosition += np.array([1, -1])
            
            #down and right
            elif diff[0] == -2 and diff[1] == 1 or diff[0] == -1 and diff[1] == 2:
                #print("down and right")
                self.tailPosition += np.array([-1, 1])
            
            #down and left
            elif diff[0] == -2 and diff[1] == -1 or diff[0] == -1 and diff[1] == -2:
                #print("down and left")
                self.tailPosition += np.array([-1, -1])
                
            
            # move left, right, up or down
            elif diff[0] == 2: # move down or up
                self.tailPosition += np.array([1, 0])
            elif diff[0] == -2:
                self.tailPosition += np.array([-1, 0]) 
                
            #move tail
            elif diff[1] == 2: # move down or up
                self.tailPosition += np.array([0, 1])
            elif diff[1] == -2:
                #print("move left")
                self.tailPosition += np.array([0, -1])
            
            #print(instruction)
            #print(self.tailPosition)
            self.grid[self.tailPosition[0], self.tailPosition[1]] = 1
            
            
            
        
        

In [9]:
gameBoard = np.zeros((5,6), dtype = int)

In [10]:
currentGame = Game(gameBoard, [0,0])
currentGame.gameStart()
currentGame.grid

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
instructions = d.split("\n")

In [12]:
#print(currentGame.tailPosition)
for instruction in instructions:
    currentGame.moveHead(instruction)

In [13]:
currentGame.grid

array([[1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 0]])

In [14]:
currentGame.headPosition

array([2, 2])

In [15]:
sum(sum(currentGame.grid))

13

# Challenge data

In [16]:
file = "challenge 09 input.txt"
with open(file) as f:
    challenge9Data = f.read()

In [17]:
howBigIsMyGrid(challenge9Data)

dimensions are: Height 331start x = 27 Width 257start y = 152


In [18]:
gameBoard = np.zeros((330,257), dtype = int)

In [19]:
gameBoard.shape

(330, 257)

In [20]:
currentGame = Game(gameBoard, [26, 151])
currentGame.gameStart()

In [21]:
sum(sum(currentGame.grid))

1

In [22]:
instructions = challenge9Data.split("\n")

In [23]:
#print(currentGame.tailPosition)
for instruction in instructions:
    #print(instruction)
    currentGame.moveHead(instruction)
    #print(currentGame.headPosition)

In [24]:
sum(sum(currentGame.grid))-1

6271

# --- Part 2 ---

A rope snaps! Suddenly, the river is getting a lot closer than you remember. The bridge is still there, but some of the ropes that broke are now whipping toward you as you fall through the air!

The ropes are moving too quickly to grab; you only have a few seconds to choose how to arch your body to avoid being hit. Fortunately, your simulation can be extended to support longer ropes.

Rather than two knots, you now must simulate a rope consisting of ten knots. One knot is still the head of the rope and moves according to the series of motions. Each knot further down the rope follows the knot in front of it using the same rules as before.

Now, you need to keep track of the positions the new tail, 9, visits. In this example, the tail never moves, and so it only visits 1 position. However, be careful: more types of motion are possible than before, so you might want to visually compare your simulated rope to the one above.

Now, the tail (9) visits 36 positions (including s) at least once.

Simulate your complete series of motions on a larger rope with ten knots. __How many positions does the tail of the rope visit at least once?__

In [90]:
class Game:
    def __init__(self, gameBoard, start):
        self.start = start
        self.startPosition = self.start
        self.headPosition = self.start
        self.tailPosition = []
        self.grid = gameBoard
        

    def gameStart(self):
        self.grid[self.start[0], self.start[0]] = 1
        for i in range(9):
            self.tailPosition.append(self.start)
    
    def moveHead(self, instruction):
        direction, amount = instruction.split(" ")
        headLocation = self.headPosition

        #MOVE RIGHT
        if direction == "R" or direction == "L":
            verticle = 0
            if direction == "R":
                horizontal = 1
                #print("Horizontal")
            else:
                horizontal = -1
        else:
            horizontal = 0
            if direction == "U":
                verticle = 1
            else:
                verticle = -1
        
                
                
        for j in range(int(amount)):
            for i in range(9):
                if i == 0:
                    headLocation = self.headPosition

                    #move head
                    movement = np.array([verticle, horizontal])
                    headLocation += movement
                    #print("move")

                else:
                    headLocation = self.tailPosition[i-1]

                #check tail
                diff = headLocation - self.tailPosition[i]
                # move diagonally
                #print(diff[1])
                if diff[0] == 0 and diff[1] == 0:
                    #print("Don't move")
                    i
                #up and right
                elif diff[0] == 2 and diff[1] ==1 or diff[0] == 1 and diff[1] == 2:
                    self.tailPosition[i] += np.array([1, 1])

                #up and left
                elif diff[0] == 2 and diff[1] == -1 or diff[0] == 1 and diff[1] == -2:
                    #print("up and left")
                    self.tailPosition[i] += np.array([1, -1])

                #down and right
                elif diff[0] == -2 and diff[1] == 1 or diff[0] == -1 and diff[1] == 2:
                    #print("down and right")
                    self.tailPosition[i] += np.array([-1, 1])

                #down and left
                elif diff[0] == -2 and diff[1] == -1 or diff[0] == -1 and diff[1] == -2:
                    #print("down and left")
                    self.tailPosition[i] += np.array([-1, -1])


                # move left, right, up or down
                elif diff[0] == 2: # move down or up
                    self.tailPosition[i] += np.array([1, 0])
                elif diff[0] == -2:
                    self.tailPosition[i] += np.array([-1, 0]) 

                #move tail
                elif diff[1] == 2: # move down or up
                    self.tailPosition[i] += np.array([0, 1])
                elif diff[1] == -2:
                    #print("move left")
                    self.tailPosition[i] += np.array([0, -1])

                if i == 8:
                    #print(instruction)
                    #print(self.tailPosition[i])
                    #print(self.tailPosition[i-1])
                    t = self.tailPosition[i]
                    #print(t)
                    self.grid[t[0], t[1]] = 1
            

In [91]:
currentGame.tailPosition[1] - currentGame.tailPosition[2]

array([0, 0])

In [92]:
gameBoard = np.zeros((330,257), dtype = int)
currentGame = Game(gameBoard, np.array([26, 151]))
currentGame.gameStart()

In [93]:
#print(currentGame.tailPosition)
for instruction in instructions:
    #print(instruction)
    currentGame.moveHead(instruction)
    #print(currentGame.headPosition)

In [94]:
currentGame.headPosition

array([303,  85])

In [95]:
sum(sum(currentGame.grid))

7149